scraper:
  # how many times to retry page scraping
  # initial invocation is not counted here
  retry_times: 2

etf:
  # specifies directory for caching etf holdings
  cache_name: etfs/
  target: tickers-etfs.csv

# specifies which urls to scrape, how to name tickers and where to cache them
screeners:
  - name: "Winners 1"
    cache_name: runs/winners1/
    urls:
      - "https://finance.yahoo.com/screener/7a712692-7bfc-4a53-92df-7607289e916a"

  - name: "Winners 5"
    cache_name: runs/winners5/
    urls:
      - "https://finance.yahoo.com/screener/fbf0a208-739c-4336-8100-e56f17ab01ab"

  - name: "Winners 10"
    cache_name: runs/winners10/
    urls:
      - "https://finance.yahoo.com/screener/b4204420-30b5-4e54-b889-dae9196de206"

  - name: "Winners 100"
    cache_name: runs/winners100/
    urls:
      - "https://finance.yahoo.com/screener/09431cb1-93db-4cfc-836e-26d6142cfa14"

  - name: "Loosers 1"
    cache_name: runs/loosers1/
    urls:
      - "https://finance.yahoo.com/screener/19949fe1-fe80-4d3e-b960-3a3c3c0d108f"

  - name: "Loosers 5"
    cache_name: runs/loosers5/
    urls:
      - "https://finance.yahoo.com/screener/e361b765-6a1c-4e2d-b16c-39b9547c0f6f"

  - name: "Loosers 10"
    cache_name: runs/loosers10/
    urls:
      - "https://finance.yahoo.com/screener/09324041-bb7b-464e-96a9-61fa4e84f48f"

  - name: "Loosers 100"
    cache_name: runs/loosers100/
    urls:
      - "https://finance.yahoo.com/screener/b03f0d70-20ba-4796-8c5e-20bd3e6a9ed3"

  - name: "Random 1"
    cache_name: runs/random1/
    urls:
      - "https://finance.yahoo.com/screener/77abaf9c-8923-408e-ab93-9e6f7c21563f"

  - name: "Random 5"
    cache_name: runs/random5/
    urls:
      - "https://finance.yahoo.com/screener/0c843e2d-2d90-4f39-a3aa-eca119051cd8"

  - name: "Random 10"
    cache_name: runs/random10/
    urls:
      - "https://finance.yahoo.com/screener/c2f52d5b-078c-43ea-ad73-0de929180492"

  - name: "Random 100"
    cache_name: runs/random100/
    urls:
      - "https://finance.yahoo.com/screener/8907a7dd-4470-4fde-990c-98c752dd2b53"

ignored_tickers:
  # file for storing ignored tickers
  # contains date and reason for ignore
  target: tickers-ignored.csv

tickers:
  # specifies directory where to story downloaded information about the ticker
  cache_name: tickers/
  target: tickers.csv

telegram:
  # specify if we should report success/error states to telegram channel
  enabled: true
