scraper:
  # how many times to retry page scraping
  # initial invocation is not counted here
  retry_times: 2

etf:
  # specifies directory for caching etf holdings
  cache_name: etfs/

yfinance:
  cache_name: .cache-yfinance
  backend: filesystem
  expire_after_days: 5

tickers:
  cache_name: tickers/
  balance_cache_name: tickers-balance/
  target: tickers.csv
  filter:
    FinancialsCurrentRatio: 0.5

screeners:
  - name: Winners
    cache_name: runs/winners/
    urls:
      - "https://finance.yahoo.com/screener/1d954b8e-a9f3-4e02-8314-2587f8029736"
      - "https://finance.yahoo.com/screener/c98302b7-934a-49c6-beeb-ba58b7a83a39"

  - name: Loosers
    cache_name: runs/loosers/
    urls:
      - "https://finance.yahoo.com/screener/e5b8bbee-e004-46ce-86dc-ea8c422f3ac7"
      - "https://finance.yahoo.com/screener/197f7d16-cd60-4df9-ab7f-fb1867736c98"

  - name: Random
    cache_name: runs/random/
    urls:
      - "https://finance.yahoo.com/screener/77abaf9c-8923-408e-ab93-9e6f7c21563f"

  - name: "Random 5"
    cache_name: runs/random5/
    urls:
      - "https://finance.yahoo.com/screener/0c843e2d-2d90-4f39-a3aa-eca119051cd8"

  - name: "Random 10"
    cache_name: runs/random10/
    urls:
      - "https://finance.yahoo.com/screener/c2f52d5b-078c-43ea-ad73-0de929180492"

telegram:
  enabled: true
