scraper:
  retry_times: 2
  sleep_after_click: 1
  min_current_ratio: 0.5
  min_trading_days: 7

ignored_tickers:
  target: tickers-ignored.csv

revive:
  ignore_after_days: 32
  sleep: 2

etf:
  cache_name: etfs/

tickers:
  refresh_in_days: 3
  refresh_limit: 500
  cache_name: tickers/
  target: tickers.csv

giga:
  - name: Giga 1-5
    target: tickers-giga-1-5.csv
    url: https://finance.yahoo.com/research-hub/screener/b783c44f-13f2-4d87-bda2-d399b0c4abb9?count=100

  - name: Giga 5-10
    target: tickers-giga-5-10.csv
    url: https://finance.yahoo.com/research-hub/screener/2f8576d2-b0b7-4ebe-bac1-6be25e36d4e2?count=100

  - name: Giga 10-100
    target: tickers-giga-10-100.csv
    url: https://finance.yahoo.com/research-hub/screener/961b7d7a-95ee-48ac-babe-532eebdb1a5d?count=100

screeners:
  - name: Winners 1
    cache_name: runs/winners1/
    url: https://finance.yahoo.com/research-hub/screener/7a712692-7bfc-4a53-92df-7607289e916a?count=100

  - name: Winners 5
    cache_name: runs/winners5/
    url: https://finance.yahoo.com/research-hub/screener/fbf0a208-739c-4336-8100-e56f17ab01ab?count=100

  - name: Winners 10
    cache_name: runs/winners10/
    url: https://finance.yahoo.com/research-hub/screener/b4204420-30b5-4e54-b889-dae9196de206?count=100

  - name: Winners 30
    cache_name: runs/winners30/
    url: https://finance.yahoo.com/research-hub/screener/ae5ec646-e73d-4133-b785-a4668b6c366c?count=100

  - name: Winners 50
    cache_name: runs/winners50/
    url: https://finance.yahoo.com/research-hub/screener/05701f22-6e63-4d76-af38-18a2ca0abe38?count=100

  - name: Winners 70
    cache_name: runs/winners70/
    url: https://finance.yahoo.com/research-hub/screener/2ee39be9-0152-467b-8a4e-4296d3b9f3ed?count=100

  - name: Winners 100
    cache_name: runs/winners100/
    url: https://finance.yahoo.com/research-hub/screener/946a6a6b-6dc7-4deb-9749-be3923536203?count=100

  - name: Loosers 1
    cache_name: runs/loosers1/
    url: https://finance.yahoo.com/research-hub/screener/19949fe1-fe80-4d3e-b960-3a3c3c0d108f?count=100

  - name: Loosers 5
    cache_name: runs/loosers5/
    url: https://finance.yahoo.com/research-hub/screener/e361b765-6a1c-4e2d-b16c-39b9547c0f6f?count=100

  - name: Loosers 10
    cache_name: runs/loosers10/
    url: https://finance.yahoo.com/research-hub/screener/09324041-bb7b-464e-96a9-61fa4e84f48f?count=100

  - name: Loosers 30
    cache_name: runs/loosers30/
    url: https://finance.yahoo.com/research-hub/screener/62b1e0d2-04d7-4fc6-9304-df45b1b25da5?count=100

  - name: Loosers 50
    cache_name: runs/loosers50/
    url: https://finance.yahoo.com/research-hub/screener/049896cc-2fc9-4428-9c58-5a2cb0cb0bf6?count=100

  - name: Loosers 70
    cache_name: runs/loosers70/
    url: https://finance.yahoo.com/research-hub/screener/7b4b12b5-78d8-4e46-a514-156c9da39aee?count=100

  - name: Loosers 100
    cache_name: runs/loosers100/
    url: https://finance.yahoo.com/research-hub/screener/1c20cb1c-c66f-4bbb-b0db-0825cff38b85?count=100

  - name: Random 1
    cache_name: runs/random1/
    url: https://finance.yahoo.com/research-hub/screener/77abaf9c-8923-408e-ab93-9e6f7c21563f?count=100

  - name: Random 5
    cache_name: runs/random5/
    url: https://finance.yahoo.com/research-hub/screener/0c843e2d-2d90-4f39-a3aa-eca119051cd8?count=100

  - name: Random 10
    cache_name: runs/random10/
    url: https://finance.yahoo.com/research-hub/screener/c2f52d5b-078c-43ea-ad73-0de929180492?count=100

  - name: Random 30
    cache_name: runs/random30/
    url: https://finance.yahoo.com/research-hub/screener/eab7f7c7-a542-4ea5-9f96-e0a56cdb8045?count=100

  - name: Random 50
    cache_name: runs/random50/
    url: https://finance.yahoo.com/research-hub/screener/bbbaec89-7f51-47c7-804e-63cca94eaecf?count=100

  - name: Random 70
    cache_name: runs/random70/
    url: https://finance.yahoo.com/research-hub/screener/037d2f0f-ca64-4825-96eb-bc55cd4d38bd?count=100

  - name: Random 100
    cache_name: runs/random100/
    url: https://finance.yahoo.com/research-hub/screener/949fbfa3-eb9f-49c9-8f3c-2abb70e8a7bd?count=100

  - name: Random 120
    cache_name: runs/random120/
    url: https://finance.yahoo.com/research-hub/screener/d2e2f40d-a6ed-42c9-b977-58a139b6fa91?count=100
