version: 1
disable_existing_loggers: False

formatters:
  short_formatter:
    format: "%(asctime)s - %(message)s"
  simple_formatter:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: short_formatter
    stream: ext://sys.stdout

loggers:
  __main__:
    level: DEBUG
    handlers: [console_handler]
    propagate: no

  screeners:
    level: DEBUG
    handlers: [console_handler]
    propagate: no

root:
  level: WARNING
  handlers: [console_handler]
