name: aggregate

on:
  workflow_dispatch:
  workflow_run:
    workflows: [tickers]
    types: [completed]

permissions:
  contents: write

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: ./run aggregate
      - run: ./run reports
      - uses: ./.github/actions/push
        with:
          message: "chore(tickers): aggregate and reports"

