name: Aggregate

on:
  workflow_dispatch:

  # workflow_run:
  #   workflows: [Ignore]
  #   types: [completed]

permissions:
  contents: write

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: |
          ./run aggregate

          git add .

          git commit --allow-empty -m "chore(aggregate): update"
          git push
