name: Aggregate

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: [Tickers]
  #   types: [completed]

permissions:
  contents: write

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: |
          ./run aggregate

          git add ./tickers.csv
          git add ./tickers-ignored.csv
          git add ./first-seen/

          git commit --allow-empty -m "chore(aggregate): update"
          git push
