name: 'Aggregate'

on:
  workflow_dispatch:

  # workflow_run:
  #   workflows: ["Tickers"]
  #   types:
  #     - completed

permissions:
  contents: 'write'

jobs:
  aggregate:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-python@v5'
        with:
          python-version: '3.12.3'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - run: ./run aggregate

      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add ./tickers.csv
          git add ./tickers-ignored.csv
          git add ./first-seen/

          git commit --allow-empty -m "chore(aggregate): update"
          git push
