name: Scrape ETF

on:
  workflow_dispatch:
  schedule:
    - cron: '00 06 * * 6'

permissions:
  contents: write

jobs:
  etf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: |
          ./run etf '${{ secrets.cookies }}'

          git add ./etfs

          git commit --allow-empty -m 'chore(etf): update etf holdings'
          git push
