name: 'Scrape ETF Holdings'

on:
  workflow_dispatch:

  schedule:
    - cron: '00 06 * * 6'

permissions:
  contents: 'write'

jobs:
  etf:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-python@v5'
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: |
          pip install -r requirements.txt
          python -m playwright install chromium

      - run: ./run etf '${{ secrets.cookies }}'

      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add ./etfs

          git commit --allow-empty -m 'chore(etf): update etf holdings'
          git push

      - run: ./run notify -- "🟢 ETF holdings updated" "${{ secrets.telegram_token }}" "${{ secrets.telegram_channel }}"
