name: Scrape Giga 5-10

on:
  workflow_dispatch:
  workflow_run:
      workflows: [Scrape Giga 1-5]
      types: [completed]

permissions:
  contents: write

jobs:
  giga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: |
          ./run giga "${{ secrets.cookies }}" 1

          git add ./tickers-giga*.csv

          git commit --allow-empty -m "chore(giga 5-10): scrape"
          git push

