name: Scrape Giga 10-100

on:
  workflow_dispatch:
  schedule:
    - cron: '00 13 * * 0'

permissions:
  contents: write

jobs:
  giga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: ./run giga "${{ secrets.cookies }}" 2

      - uses: ./.github/actions/push
        with:
          message: "chore(giga): 10-100 scrape"

