name: 'Scrape Giga Screeners'

on:
  workflow_dispatch:

  schedule:
    - cron: '00 09 * * 0'

permissions:
  contents: 'write'

jobs:
  scrape:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-python@v5'
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: |
          pip install -r requirements.txt
          python -m playwright install chromium

      - run: ./run giga "${{ secrets.cookies }}"

      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add ./tickers-giga*.csv

          git commit --allow-empty -m "chore(giga): scrape"
          git push
