name: 'Scrape Giga 5-10'

on:
  workflow_dispatch:

  workflow_run:
      workflows: ["Scrape Giga 1-5"]
      types:
        - completed

permissions:
  contents: 'write'

jobs:
  giga:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-python@v5'
        with:
          python-version: '3.12.3'
          cache: 'pip'

      - run: |
          pip install -r requirements.txt
          python -m playwright install chromium

      - run: ./run giga "${{ secrets.cookies }}" 1

      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add ./tickers-giga*.csv

          git commit --allow-empty -m "chore(giga 5-10): scrape"
          git push

