name: Ignore

on:
  workflow_dispatch:

  workflow_run:
    workflows: [Tickers]
    types: [completed]

permissions:
  contents: write

jobs:
  tickers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: |
          ./run ignore

          git add ./tickers-ignored.csv

          git commit --allow-empty -m "chore(ignore): update"
          git push
