name: Ignore

on:
  workflow_dispatch:

  # workflow_run:
  #   workflows: [Tickers]
  #   types: [completed]

permissions:
  contents: write

jobs:
  tickers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: ./run ignore

      - uses: ./.github/actions/push
        with:
          message: "chore(tickers): ignore"
