name: refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6-21 * * 6'

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: ./run refresh
      - uses: ./.github/actions/push
        with:
          message: "chore(tickers): refresh"
