name: Reports

on:
  workflow_dispatch:

  workflow_run:
    workflows: [Aggregate]
    types: [completed]

permissions:
  contents: write

jobs:
  reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: |
          ./run reports

          git add ./reports/

          git commit --allow-empty -m "chore(reports): update"
          git push
