name: Revive

on:
  workflow_dispatch:
  schedule:
    - cron: '00 06 * * 0'

permissions:
  contents: write

jobs:
  revive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: |
          # ./run revive "Not Found"
          # ./run revive "Missing Close Price"
          # ./run revive "Not Categorized"
          # ./run revive "Current Ratio Below 0.5"
          ./run revive "No Recent Trades"

          git add ./tickers-ignored.csv

          git commit --allow-empty -m "chore(tickers): revive"
          git push

      - run: ./run notify -- "🟢 tickers revived" "${{ secrets.telegram_token }}" "${{ secrets.telegram_channel }}"
