name: Revive

on:
  workflow_dispatch:
  schedule:
    - cron: '00 10 * * 0'

permissions:
  contents: write

jobs:
  revive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: |
          ./run revive

          git add ./tickers-ignored.csv

          git commit --allow-empty -m "chore(tickers): revive"
          git push
