name: Revive

on:
  workflow_dispatch:
  schedule:
    - cron: '00 10 * * 0'

permissions:
  contents: write

jobs:
  revive:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: ./run revive

      - uses: ./.github/actions/push
        with:
          message: "chore(tickers): revive"
