name: 'Deploy GitHub pages'

on:
  workflow_run:
    workflows: ['Scrape Yahoo screeners']
    types: ['completed']

  workflow_dispatch:

permissions:
  contents: 'read'
  pages: 'write'
  id-token: 'write'

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout sources'
        uses: 'actions/checkout@v4'

      - name: 'Setup python 3.10'
        uses: 'actions/setup-python@v5'
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 'Install depedencies'
        run: pip install -r requirements.txt

      - name: 'Generate pages'
        run: python ./yahoo-report-pages.py

      - name: 'Setup pages'
        uses: 'actions/configure-pages@v5'

      - name: 'Upload artifact'
        uses: 'actions/upload-pages-artifact@v3'
        with:
          path: './pages'

      - name: 'Deploy GitHub pages'
        id: 'deployment'
        uses: 'actions/deploy-pages@v4'
