name: Summary

on:
  workflow_dispatch:
  schedule:
    - cron: '00 14 * * 0'

permissions:
  contents: write

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: |
          ./run summary

          git add ./summary.md

          git commit --allow-empty -m "chore(summary): update"
          git push
