name: 'Update tickers'

on:
  workflow_dispatch:

  schedule:
    - cron: '00 06 * * 1-5'

permissions:
  contents: 'write'

jobs:
  tickers:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-python@v5'
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - run: ./run tickers 3

      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add ./tickers/

          git commit --allow-empty -m "chore(tickers): update"
          git push
