name: 'Tickers'

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Scrape"]
    types:
      - completed

permissions:
  contents: 'write'

jobs:
  tickers:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: ./run tickers 0

      - run: |
          git add ./tickers/
          git add ./tickers-ignored.csv

          git commit --allow-empty -m "chore(tickers): update"
          git push
