name: tickers

on:
  workflow_dispatch:
  workflow_run:
    workflows: [scrape]
    types: [completed]

permissions:
  contents: write

jobs:
  tickers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: ./run tickers
      - run: ./run ignore
      - uses: ./.github/actions/push
        with:
          message: "chore(tickers): update and ignore"
